name: Checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: list toolcache
        run: get-childitem -Path 'C:\hostedtoolcache\windows\go'
        shell: powershell

      #- name: disable realtime antivirus
      #  run: Set-MpPreference -DisableRealtimeMonitoring $true
      #  shell: powershell

      #- name: disable 8dot3
      #  run: fsutil 8dot3name set 1
      #  shell: powershell

      #- run: |
      #   choco install windows-performance-toolkit
      #   "C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -start -on LOADER+PROC_THREAD+DISK_IO+HARD_FAULTS+DPC+INTERRUPT+CSWITCH+PERF_COUNTER+FILE_IO_INIT+REGISTRY
      #  shell: cmd
    
      - uses: actions/setup-go@v4
        with:
          go-version-file: .go-version
          cache: false

      #- run: |
      #    "c:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -d tmp.etl
      #  shell: cmd

      #- name: Archive ETL
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: WPP
      #    path: tmp.etl

      #- run: make test
